// Typed access to the generated changelog. The data comes from the GitHub Releases of every
// CoreGrid repo and is regenerated by `scripts/generate-changelog.mjs` before start/build.
import data from './generated/changelog.json';

export type ChangelogBlock =
  | {type: 'paragraph' | 'heading' | 'quote'; text: string}
  | {type: 'list'; ordered: boolean; start?: number; items: string[]}
  | {type: 'code'; lang: string; code: string};

export type ChangelogSection = {
  heading: string;
  blocks: ChangelogBlock[];
};

export type ChangelogAsset = {name: string; url: string; size: number};

export type ChangelogRelease = {
  id: string;
  product: string;
  version: string;
  name: string;
  tagline: string;
  date: string;
  prerelease: boolean;
  githubUrl: string;
  sourceUrl: string;
  assets: ChangelogAsset[];
  summary: string[];
  contributors: string[];
  sections: ChangelogSection[];
};

export type ChangelogProduct = {
  id: string;
  label: string;
  repo: string;
  releases: ChangelogRelease[];
};

export const owner: string = data.owner;
export const products = data.products as unknown as ChangelogProduct[];

/** Every release across all products, newest first. */
export const releases: ChangelogRelease[] = products
  .flatMap((product) => product.releases)
  .sort((a, b) => b.date.localeCompare(a.date));

/** IDs of the newest stable release of each product. */
export const latestIds = new Set(
  products.map((product) => product.releases.find((release) => !release.prerelease)?.id).filter(Boolean),
);

export const productById = new Map(products.map((product) => [product.id, product]));
